# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
paginate:         10

# Setup
title:            MakinGIANTS
tagline:          'MakinGIANTS'
description:      'Blog'
mainurl:          http://www.makingiants.com
url:              http:/blog.makingiants.com
baseurl:          /

author:
  name:           'Daniel Gomez Rico'
  url:            https://github.com/makingiants/blog

# Custom vars
version:          3.1.3

github:
  repo:           https://github.com/poole/hyde

gems:
 - emoji_for_jekyll
 - jekyll-paginate
 - jekyll-gist