title: MakinGIANTS
description: Compilation of projects and code made for fun!

url: http://www.makingiants.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Our Android Apps
   url: https://play.google.com/store/search?q=makingiants 
 - title: Awesome Mobile
   url: /awesome_mobile

gems:
 - emoji_for_jekyll
 - jekyll-compass

social:
   github: makingiants
   twitter: danielgomezrico
   #facebook: 
   email: danielgomezrico@gmail.com

google_analytics: "UA-36813115-3"
