title: MakinGIANTS
description: Compilation of projects and code made for fun!

url: http://www.makingiants.com
baseurl: "/blog"
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: http://www.makingiants.com
 - title: Awesome Mobile
   url: /awesome_mobile

gems:
 - emoji_for_jekyll
 - jekyll-compass
 - jekyll-gist

social:
   github: makingiants
   twitter: dgomezri
   #facebook:
   email: danielgomezrico@gmail.com

google_analytics: "UA-36813115-3"
