# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
paginate:         5

# Setup
title:            MakinGIANTS
tagline:          'MakinGIANTS'
description:      'Blog'
url:              http://blog.makingiants.com
baseurl:          /

author:
  name:           'Daniel Gomez Rico'
  url:            https://github.com/makingiants

# Custom vars
version:          3.1.3

github:
  repo:           https://github.com/poole/hyde

gems:
 - emoji_for_jekyll
 - jekyll-paginate
 - jekyll-gist